Remove pixels on non-event and add onBidWon
SublimeSkinz/Prebid.js pull request #22
Opened 2020-04-02 11:16 UTC by SublimeLeo

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Changes: 
- Removed pixels
- Added onBidWon event pixel

Test parameters for validating bids
```
{
  bidder: 'sublime',
  params: {
    zoneId: 1
  }
}
```

2020-04-07 07:57 UTC, SublimeJeremy commented
@SublimeLeo C'est bien rebase depuis le master de https://github.com/prebid/Prebid.js ?

2020-04-07 08:10 UTC, SublimeLeo commented
@SublimeJeremy Maintenant oui!

2020-04-08 08:12 UTC, ghourlier approved these changes

2020-04-08 08:16 UTC, fgcloutier commented on modules/sublimeBidAdapter.js
> +  sendEvent('bidwon', true);
Ne correspond pas à la signature de sendEvent.

```suggestion
  sendEvent('bidwon');
```

2020-04-08 08:16 UTC, fgcloutier commented on modules/sublimeBidAdapter.js
> +  sendEvent('bidtimeout', true);
Idem.

```suggestion
  sendEvent('bidtimeout');
```

2020-04-08 08:22 UTC, ghourlier requested changes

2020-04-08 08:22 UTC, hellsingblack commented on modules/sublimeBidAdapter.js
> +export function sendEvent(eventName) {
tu utilise un deuxieme parametre à l'apelle pourquoi ?

2020-04-08 09:26 UTC, fgcloutier approved these changes

2020-04-08 11:46 UTC, SublimeJeremy approved these changes

2020-04-08 12:23 UTC, merged