DL-1286 : Add bida and onbidwon
SublimeSkinz/Prebid.js pull request #23
Opened 2020-04-02 12:21 UTC by SublimeLeo

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- Changed bid pixel to bida
- Add onBidWon method

```
{
  bidder: 'sublime',
  params: {
    zoneId: 1
  }
}
```

https://sublimeskinz.atlassian.net/browse/DL-1286

2020-04-02 12:49 UTC, SublimeJeremy submitted a review, later dismissed

2020-04-02 14:35 UTC, SublimeJeremy requested changes
Please increment version

2020-04-02 15:27 UTC, SublimeLeo commented
@SublimeJeremy Done ! 👍

2020-04-02 17:42 UTC, ghourlier approved these changes

2020-04-03 07:20 UTC, SublimeJeremy approved these changes

2020-04-03 08:56 UTC, merged